'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace FormattingServicesExample.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As FormattingServicesExample.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New FormattingServicesExample.Properties.Settings())), FormattingServicesExample.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return FormattingServicesExample.Properties.Settings.defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)>
        <Global.System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=XtraCars;Integrated Security=True")>
        Public ReadOnly Property XtraCarsConnectionString As String
            Get
                Return(CStr((Me("XtraCarsConnectionString"))))
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)>
        <Global.System.Configuration.DefaultSettingValueAttribute("Data Source=ZAYTSEV_XP;Initial Catalog=XtraCars;Persist Security Info=True;User I" & "D=sa;Password=123")>
        Public ReadOnly Property XtraCarsConnectionString1 As String
            Get
                Return(CStr((Me("XtraCarsConnectionString1"))))
            End Get
        End Property
    End Class
End Namespace
